version: '2'

services:

  api:
    container_name: 'skillustrator-api-dev'
    image: 'excellalabs/skillustrator-api-dev'
    build:
      context: ./API
      dockerfile: Dockerfile
    volumes:
      - ./API:/app
    ports:
      - "5000:5000"
    entrypoint: ["sh", "./scripts/go.sh"]
    depends_on:
      - postgres
    networks:
      - aspnetcoreapp-network

  ui:
    container_name: 'skillustrator-ui-dev'
    image: 'excellalabs/skillustrator-ui-dev'
    build:
      context: ./UI
      dockerfile: Dockerfile.AppAndAngular2
    command: npm start
    volumes:
      - ./UI:/app
      - /app/node_modules # map container's node_modules directory back into the host's source, otherwise npm install would have to be run locally
    ports:
      - "4200:4200"
    links:
      - api
    depends_on:
      - api
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'skillustrator-postgres-dev'
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge

volumes:
  postgres: {}