version: '2'

services:

  api:
    container_name: 'skillu_api'
    image: 'excellalabs/skillustrator-api'
    build:
      context: ./API
      dockerfile: Dockerfile
    volumes:
      #- ./API:/app
      - C:/dev/Skills%20Illustrator/API:/app
    ports:
      - "5000:5000"
    entrypoint: ["sh", "./scripts/go.sh"] 
    depends_on:
      - postgres
    networks:
      - aspnetcoreapp-network

  # ui:
  #   container_name: 'skillu_ui'
  #   image: 'excellalabs/skillustrator-ui'
  #   build:
  #     context: ./UI
  #     dockerfile: Dockerfile.AppAndAngular2
  #   volumes:
  #     - C:/dev/Skills%20Illustrator/UI:/app
  #   ports:
  #     - "4200:4200"
  #   links:
  #     - api
  #   depends_on:
  #     - api
  #   networks:
  #     - aspnetcoreapp-network

  postgres:
    container_name: 'skillustrator-postgres'
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge

volumes:
  postgres: {}