version: '2'

services:

  api:
    container_name: 'skillu_api'
    image: 'msexcella:aspnetcore-dev-env'
    build:
      context: ./API
      dockerfile: Dockerfile
    volumes:
      - ./API:/app
    ports:
      - "5000:5000"
    entrypoint: ["sh", "./scripts/go.sh"] 
    depends_on:
      - postgres
    networks:
      - aspnetcoreapp-network

  ui:
    container_name: 'skillu_ui'
    image: 'msexcella:angular-dev-env'
    build:
      context: ./UI
      dockerfile: Dockerfile
    volumes:
      - ./UI:/app
    ports:
      - "4200:4200"
    links:
      - api
    depends_on:
      - api
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge

volumes:
  postgres: {}