version: '2'

services:

  api:
    container_name: 'skillustrator-api-dev'
    image: 'excellalabs/skillustrator-api-dev'
    build:
      context: ./API
      dockerfile: Dockerfile.Prod
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:5000"
    networks:
      - aspnetcoreapp-network
    depends_on:
      - postgres
    links:
      - postgres

  ui:
    container_name: 'skillustrator-ui-dev'
    image: 'excellalabs/skillustrator-ui-dev'
    build:
      context: ./UI
      dockerfile: Dockerfile.AppAndAngular2
    ports:
      - "80:4200"
    networks:
      - aspnetcoreapp-network
    depends_on:
      - api
    links:
      - api

  postgres:
    container_name: 'skillustrator-postgres-dev'
    image: postgres:9.6.3
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge

volumes:
  postgres: {}