version: '2'

services:

  web:
    container_name: 'skillu'
    image: 'msexcella:aspnetcore-dev-env'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
     - "5000:5000"
    entrypoint: ["sh", "./scripts/go.sh"] 
    depends_on:
     - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password
    ports:
     - "5432:5432"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge

volumes:
  postgres: {}